import type { Metadata } from 'next';
import "./globals.css";
import { LiffProvider } from './components/LiffProvider';
import { Inter as FontSans } from "next/font/google";
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'LIFF App for App Router',
  description: 'Generated by create next app',
};

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <LiffProvider liffId={process.env.NEXT_PUBLIC_LIFF_ID || ''}>
          {children}
        </LiffProvider>
      </body>
    </html>
  );
}
